# permet de créer une image sur la base d'une ditribution debian puis d'installer wget et de faire le ménage pour réduire la taille de l'image
FROM debian:buster 
RUN apt-get update && \ 
	apt-get install -y wget && \ 
	apt-get clean && \ 
	rm -rf /var/lib/apt/lists/*