version: '3.8'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - movie-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: moviedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge